### ISSUE TITLE
KoPackageMatchingPathProviderCore.hasMatchingPath fails on windows

### ISSUE THREAD

**Issue by Hoagiex** [LemonAppDev/konsist#865]
### Discussed in https://github.com/LemonAppDev/konsist/discussions/864

<div type='discussions-op-text'>

<sup>Originally posted by **Hoagiex** February  8, 2024</sup>
### Tell us what version of Konsist you use.

0.13.0

### Was this something which used to work for you, and then stopped?

0.13.0 is the first version we used.

### Describe the problem

hasMatchingPath fails on windows, due to having a different path separator

`    override val hasMatchingPath: Boolean
        get() =
            path
                .replace("/", ".")
                .endsWith(fullyQualifiedName + "." + containingFile.nameWithExtension)`

### Actual behaviour

Test succeeds on (e.g. Macos), but fails on windows

### Expected behaviour

Succeeds on windows</div>

**Comment by igorwojda** [comment]
Thx for detailed report. Closing this ticket as we are using JIRA to report issues.
Fix targeted for the next release
https://lemonappdev.atlassian.net/browse/KON-592
